---
galaxy_info:
  author: CCDC Range
  description: Windows SMB file server with intentional CCDC practice vulnerabilities
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - windows
    - smb
    - fileserver
    - ccdc
dependencies: []
